name: Azure Pipelines
variables:
  # Azure Resource Manager service connection for pipelines
  azureServiceConnectionId: '02cc2bd2-9ade-452a-94a7-4052dfd43b29'

  # Python version: 3.7.6
  python.version: '3.7.6'

  # Agent VM image name
  vmImageName: 'myPackerImage'

  # Web app name
  webAppName: 'udacity-azure-course-project3-test-app-AppService'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Environment name
  environmentName: 'test'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-20.04
    steps:

    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBByBaEbrJf+v9agEtM6g/LruTudlDznQ/Dca0BW/awH3/lX26tI/a6kDg90tOCOZIMotbavb3ABKJfkaDvFFGtI='
        sshPublicKey: '$(udacityPubKey)'
        sshKeySecureFile: 'udacity_id_rsa'

    - task: DownloadSecureFile@1
      name: udacity_public_key
      displayName: 'Download Public Key'
      inputs:
        secureFile: 'udacity_id_rsa.pub'
        
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '0.14.7'

    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        backendServiceArm: 'anja-subscription-service-connection'
        backendAzureRmResourceGroupName: 'tstate'
        backendAzureRmStorageAccountName: 'tstate19841'
        backendAzureRmContainerName: 'tstate'
        backendAzureRmKey: 'terraform-project3.tfstate'

    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        commandOptions: '-var "public_key_path=$(udacity_public_key.secureFilePath)"'
        environmentServiceNameAzureRM: 'anja-subscription-service-connection'

    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi

    - task: CopyFiles@2
      displayName: 'Copy Postman Test definitions to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: 'automatedtesting/postman/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

- stage: Deploy
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: ubuntu-20.04
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'anja-subscription-service-connection'
              appName: $(webAppName)
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip

          - task: Bash@3
            displayName: 'Install Postman & Newman'
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
                sudo snap install postman
                sudo npm install -g newman
                sudo npm install newman-reporter-junitfull -g                   
    
          - task: Bash@3
            displayName: 'Run Regression Test Suite'
            inputs:
              workingDirectory: '$(Build.ArtifactStagingDirectory)'
              targetType: 'inline'
              script: |
                #! /bin/bash
                newman run RegressionTest.json -e MyEnv.json -r cli,junitfull --reporter-junitfull-export JUnitReport.xml

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/JUnitReport.xml'
              testRunTitle: 'Publish test results'
              searchFolder: '$(System.DefaultWorkingDirectory)'

          # TODO: Execute test suite for JMeter

  - deployment: VMDeploy
    displayName: 'Deploy VM'
    environment:
      name:  'TEST'
      resourceType: VirtualMachine
      tags: test, packer-created-vm
    strategy:
      runOnce:
        deploy:
          steps:

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                #! /bin/bash
              
                sudo apt-get upgrade -y
                sudo apt-get install python3-pip -y
                sudo apt-get install unzip -y
                sudo apt-get install -y chromium-browser
                pip3 install selenium
                export PATH=$PATH:some/path
      
          # TODO: Execute test suite for Selenium  
