name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-20.04
    steps:

    - task: Bash@3
      displayName: 'Double check directory contents Build Stage'
      inputs:
        workingDirectory: 'automatedtesting/postman'
        targetType: 'inline'
        script: |
          #! /bin/bash
          pwd
          find .

- stage: Deployment
  jobs:
  - job: FakeRestAPI
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: Bash@3
      displayName: 'Double check directory contents Deploy Stage'
      inputs:
        targetType: 'inline'
        script: |
          #! /bin/bash
          pwd
          find .